server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://172.16.1.120:3306/db_haojiao?useUnicode=true&characterEncoding=UTF-8
#    url: jdbc:mysql://localhost:3306/db_haojiao?useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root1234

debug:
  true
#logging:
#  level: debug

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
#  config-location: classpath:spring-mybatis.xml
